### ISSUE TITLE
Questions on gulp boilerplate

### ISSUE THREAD

**Issue by melbournevijay** [cferdinandi/gulp-boilerplate#40]
Hi Chris,

I always used tools like Brackets to work with kraken, I am now loving the gulp boiler plate. Can you please answer a couple of questions and help a gulp newbie:

1. I love how the Docs are implemented, i tried to do something similar for html files and failed - any help/code most appreciated. 

    Idea: All `.md` files in src folder are combined with header and footer files in `src/templates` folder and saved to `dist` folder as `.html` files. Can we add comments at top of `.md` file so that each generated file has correct meta-description and title.

2. Implementing Add ons: Whats you process for implementing an add on (eg drop down menu), do you copy in `.css` and `.js` files into src/css an `src/js` folder individually and then `@import` them?

3. Tests: don't understand jasmine and karma - any notes or tuts you can point me to?
As always, many thanks for sharing...

Cheers,
vj

**Comment by cferdinandi** [comment]
Hi dude, sorry for the delay in getting back to you on this!

1. You don't *need* to use `.md` files. You can put `.html` files directly in `src/docs` as well. The only thing to mindful of: they should only be the body content, everything up to and including the opening `<body>` and closing `</body>` tag are included in `_header.html` and `_footer.html`.

    I looked into some sort of variable system for creating unique titles and came up short, and given how I use the docs system, didn't feel it was worth investigating further. If you're looking for a true static site generator, you can do far better than the Kraken docs system.

2. I just copy/paste the `src` versions of the add-ons into `src/js` and `src/sass/components` as appropriate (don't forget to add a reference to the Sass files in `main.scss`. For third-party stuff, I'll take the compiled distribution versions, but use the same process as noted above.

3. I suck at these, too, and only have half a clue what I'm doing because someone at a previous job hand-held me through the process the first few times. Basically, though, Karma is a JS process runner (it opens a headless browsers, runs a bunch of tests as specified using the tool of choice, and spits out a report). Jasmine is a testing tool (there are others) that uses some boolean statements. You tell it what to do at the start, then things to check for. (Ex. after initializing, is there a class on the `<html>` element, and is it the right one. Returns `true` if it is, and `false` if it's not). It's a **lot** more complicated than that, though, and I slack at writing unit tests as a result.

    At the moment, I just drop the existing `spec-*` ones for my add-ons into the `tests/spec` directory.

Sorry I wasn't of that much help!
